FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

RUN chsh -s /bin/bash

SHELL ["/bin/bash", "-c"]

WORKDIR /home/

RUN apt-get update
RUN apt-get install -y wget bzip2   
RUN apt-get clean

#mercurial subversion ca-certificates git libxrender1 libglib2.0-0 libxext6 libsm6

RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh -O ~/anaconda.sh && \
        /bin/bash ~/anaconda.sh -b -p /opt/conda && \
        rm ~/anaconda.sh && \
        ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
        echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
        find /opt/conda/ -follow -type f -name '*.a' -delete && \
        find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
        /opt/conda/bin/conda clean -afy

ENV PATH /opt/conda/bin:$PATH

# setup conda virtual environment
COPY ./DiffDock/environment.yml ./environment.yml

RUN conda update conda \
    && conda env create --name DiffDock -f ./environment.yml

RUN echo "conda activate DiffDock" >> ~/.bashrc
ENV PATH /opt/conda/envs/DiffDock/bin:$PATH
ENV CONDA_DEFAULT_ENV $DiffDock

COPY ./DiffDock ./

RUN pip install -e ./esm/.

CMD ["bash"]