name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f DiffDock -f DiffDock_GPU/Dockerfile_GPU_1_13
